version: "3.9"
services:
    hadoop-01:
        image: hadoop2:latest
        volumes:
          - ./etc-hadoop:/etc-hadoop
        networks:
          - hadoop-net
        hostname: hadoop-01
        tty: true
        ports:
          - "50070:50070"
          - "19888:19888"
    hadoop-02:
        image: hadoop2:latest
        volumes:
          - ./etc-hadoop:/etc-hadoop
        networks:
          - hadoop-net
        hostname: hadoop-02
        tty: true
        ports:
          - "50090:50090"
    hadoop-03:
        image: hadoop2:latest
        volumes:
          - ./etc-hadoop:/etc-hadoop
        networks:
          - hadoop-net
        hostname: hadoop-03
        tty: true
        ports:
          - "8088:8088"
    hadoop-04:
        image: hadoop2:latest
        volumes:
          - ./etc-hadoop:/etc-hadoop
        networks:
          - hadoop-net
        hostname: hadoop-04
        tty: true
    hadoop-05:
        image: hadoop2:latest
        volumes:
          - ./etc-hadoop:/etc-hadoop
        networks:
          - hadoop-net
        hostname: hadoop-05
        tty: true

networks:
    hadoop-net:
        driver: bridge
